Workshop_app/travel/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from .models import Destination, User
from . import db

mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def index():
    destinations = db.session.scalars(db.select(Destination)).all()    
    # Get the user from the database
    if '_user_id' in session:
        user = db.session.scalar(db.select(User).where(User.id==session['_user_id']))
        print(user)
        return render_template('index.html', destinations=destinations, user=user.name)
    
    return render_template('index.html', destinations=destinations)
@mainbp.route('/search')
def search():
    if request.args['search'] and request.args['search'] != "":
        print(request.args['search'])
        query = "%" + request.args['search'] + "%"
        destinations = db.session.scalars(db.select(Destination).where(Destination.description.like(query)))
        return render_template('index.html', destinations=destinations)
    else:
        return redirect(url_for('main.index'))

Workshop_app/travel/templates/base.html
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Shridhar's Travel App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
</head>

<body>
    <!-- Header -->
    <header class="bg-light border-bottom">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <!-- Your Travel App Name or Logo -->
                <a id="email-name" href="/" class="navbar-brand"> My Travel App </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar -->
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item nav-link" href="/">Destinations</a>
                        <a class="nav-item nav-link" href="#">Bookings</a>
                        <a class="nav-item nav-link" href="/destinations/create">Create Destination</a>
                        {% if user%}
                        <a class="nav-item nav-link" href="/logout">Logout {{user}}</a>
                        {% else %}
                        <a class="nav-item nav-link" href="/login">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        <!--Jumbotron-->
        {% block header %}
        {% endblock %}
    </header>

    {% block content %}

    {% endblock %}

    <footer class="d-flex flex-wrap justify-content-between align-items-center text-center p-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center" style="margin: 0px;">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <svg class="bi" width="30" height="24">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>
            <span class="mb-0 text-body-secondary">© 2023 Shridhar, IAB207 Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3">
                <a class="text-body-secondary" href="https://github.com/ShridharThorat">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="bg-black" class="bi bi-github"
                        viewBox="0 0 16 16">
                        <path
                            d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
                    </svg>
                </a>
            </li>
        </ul>
    </footer>
    <!-- Include Bootstrap JS (Popper.js and Bootstrap.js) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>

</html>

Workshop_app/travel/templates/index.html
{% extends 'base.html' %}

<!--Jumbotron-->
{% block header %}
<!--Jumbotron-->
<div class="container">
  <div class="row justify-content-center mt-5 pb-4">
    <div class="col-md-8">
      <div class="card shadow p-5 mb-5 bg-light">
        <h1 class="text-center mb-3">Find our best travel deals</h1>
        <form class="form-inline d-flex flex-nowrap" action="{{ url_for('main.search') }}">
          <input type="text" name="search" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm">
          <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block content %}
<div class="container">
  <div class="row mt-5 mb-5 justify-content-center">
    <div class="col-md-10">
      <div class="media border p-3 d-flex justify-content-start">
        <img class="align-self-center me-3" style="max-width:120px"
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Earth_Western_Hemisphere_transparent_background.png/600px-Earth_Western_Hemisphere_transparent_background.png"
          alt="Planet Earth">
        <div class="align-self-center media-body">
          <h5 class="mt-0">Find the best destinations on earth</h5>
          {% if user%}
          <!-- Add a tooltip that says "Dave is logged in" -->
          <a href="/login" class="btn btn-primary disabled">Welcome {{user}}</a>
          {% else %}
          <a href="/login" class="btn btn-primary">Join Now</a>
          {% endif %}
          
        </div>
      </div>
    </div>
  </div>

  <div class="card-group">
    {% for destination in destinations %}
    <div class="card mx-3">
      <img class="card-img-top" src="{{destination.image}}" alt="destination picture">
      <div class="card-body">
        <h5 class="card-title">{{destination.name}}</h5>
        <p class="card-text">{{destination.description}}</p>
      </div>
      <div class="card-footer"><a href="{{url_for('destination.show', id=destination.id)}}" class="btn btn-danger"> View
          Details </a></div>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock %}

Workshop_app/travel/templates/user.html
{% extends "base.html" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}

<div class="container-fluid">
    <div class="page-header">
        <h4>{{heading}}</h4>
    </div>

    <!-- flashes any messages to the user -->
    {% with messages = get_flashed_messages() %}
    {% if messages %} <!-- check if there are any messages -->
    <div class="container-fluid">
        <div class="row mt-3 mb-3">
            <div class="col-md-12">
                {% for message in messages %} <!--loop through the messages-->
                <div class="alert alert-info">{{message}}</div> <!--display as alert-->
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
    {% endwith %}

    <!-- Form rendering is simple and easy if using bootstrap -->
    <div class="col-md-6 ml-5">
        {{render_form(form)}}
    </div>

    <!-- When you have login form, then do show the user a link to register -->
    {% if heading|lower == 'login' %}
    <div class="col-md-4 mb-5 ml-5">
        <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
    </div>
    {% endif %}
</div>
{% endblock %}